---
- hosts: all
  tasks:
    - name: Login to Dockerhub
      command: "docker login -u {{ docker_hub_login_thresh.user }} -p {{ docker_hub_login_thresh.password }}"
      no_log: true

    - name: List images
      shell: "docker images --format '{% raw %}{{ .Repository }}:{{ .Tag }}{% endraw %}' | grep monasca"

    - name: Push to Docker Hub all tags
      shell: "docker push monasca/thresh:{{ zuul.tag if zuul.pipeline == 'release' else 'stable-ussuri'}}
